var searchData=
[
  ['needed_0',['needed',['../structnk__buffer.html#a6b0ea49209eaba5285b715d902c5f446',1,'nk_buffer']]],
  ['nk_5fallocator_1',['nk_allocator',['../structnk__allocator.html',1,'']]],
  ['nk_5fbegin_2',['# nk_begin',['../nuklear__window_8c.html#autotoc_md27',1,'']]],
  ['nk_5fbegin_5ftitled_3',['# nk_begin_titled',['../nuklear__window_8c.html#autotoc_md29',1,'']]],
  ['nk_5fbuffer_4',['nk_buffer',['../structnk__buffer.html',1,'']]],
  ['nk_5fbuffer_5fmarker_5',['nk_buffer_marker',['../structnk__buffer__marker.html',1,'']]],
  ['nk_5fchart_6',['nk_chart',['../structnk__chart.html',1,'']]],
  ['nk_5fchart_5fslot_7',['nk_chart_slot',['../structnk__chart__slot.html',1,'']]],
  ['nk_5fclipboard_8',['nk_clipboard',['../structnk__clipboard.html',1,'']]],
  ['nk_5fcollapse_5fstates_9',['nk_collapse_states',['../Window.html#autotoc_md26',1,'']]],
  ['nk_5fcolor_10',['nk_color',['../structnk__color.html',1,'']]],
  ['nk_5fcolorf_11',['nk_colorf',['../structnk__colorf.html',1,'']]],
  ['nk_5fcommand_12',['nk_command',['../structnk__command.html',1,'']]],
  ['nk_5fcommand_5farc_13',['nk_command_arc',['../structnk__command__arc.html',1,'']]],
  ['nk_5fcommand_5farc_5ffilled_14',['nk_command_arc_filled',['../structnk__command__arc__filled.html',1,'']]],
  ['nk_5fcommand_5fbuffer_15',['nk_command_buffer',['../structnk__command__buffer.html',1,'']]],
  ['nk_5fcommand_5fcircle_16',['nk_command_circle',['../structnk__command__circle.html',1,'']]],
  ['nk_5fcommand_5fcircle_5ffilled_17',['nk_command_circle_filled',['../structnk__command__circle__filled.html',1,'']]],
  ['nk_5fcommand_5fcurve_18',['nk_command_curve',['../structnk__command__curve.html',1,'']]],
  ['nk_5fcommand_5fcustom_19',['nk_command_custom',['../structnk__command__custom.html',1,'']]],
  ['nk_5fcommand_5fimage_20',['nk_command_image',['../structnk__command__image.html',1,'']]],
  ['nk_5fcommand_5fline_21',['nk_command_line',['../structnk__command__line.html',1,'']]],
  ['nk_5fcommand_5fpolygon_22',['nk_command_polygon',['../structnk__command__polygon.html',1,'']]],
  ['nk_5fcommand_5fpolygon_5ffilled_23',['nk_command_polygon_filled',['../structnk__command__polygon__filled.html',1,'']]],
  ['nk_5fcommand_5fpolyline_24',['nk_command_polyline',['../structnk__command__polyline.html',1,'']]],
  ['nk_5fcommand_5frect_25',['nk_command_rect',['../structnk__command__rect.html',1,'']]],
  ['nk_5fcommand_5frect_5ffilled_26',['nk_command_rect_filled',['../structnk__command__rect__filled.html',1,'']]],
  ['nk_5fcommand_5frect_5fmulti_5fcolor_27',['nk_command_rect_multi_color',['../structnk__command__rect__multi__color.html',1,'']]],
  ['nk_5fcommand_5fscissor_28',['nk_command_scissor',['../structnk__command__scissor.html',1,'']]],
  ['nk_5fcommand_5ftext_29',['nk_command_text',['../structnk__command__text.html',1,'']]],
  ['nk_5fcommand_5ftriangle_30',['nk_command_triangle',['../structnk__command__triangle.html',1,'']]],
  ['nk_5fcommand_5ftriangle_5ffilled_31',['nk_command_triangle_filled',['../structnk__command__triangle__filled.html',1,'']]],
  ['nk_5fconfiguration_5fstacks_32',['nk_configuration_stacks',['../structnk__configuration__stacks.html',1,'']]],
  ['nk_5fcontext_33',['nk_context',['../structnk__context.html',1,'']]],
  ['nk_5fconvert_5fconfig_34',['nk_convert_config',['../structnk__convert__config.html',1,'']]],
  ['nk_5fcursor_35',['nk_cursor',['../structnk__cursor.html',1,'']]],
  ['nk_5fdraw_5fnull_5ftexture_36',['nk_draw_null_texture',['../structnk__draw__null__texture.html',1,'']]],
  ['nk_5fedit_5fstate_37',['nk_edit_state',['../structnk__edit__state.html',1,'']]],
  ['nk_5fend_38',['# nk_end',['../nuklear__window_8c.html#autotoc_md31',1,'']]],
  ['nk_5fgroup_5fend_39',['# nk_group_end',['../nuklear__group_8c.html#autotoc_md81',1,'']]],
  ['nk_5fgroup_5fget_5fscroll_40',['# nk_group_get_scroll',['../nuklear__group_8c.html#autotoc_md85',1,'']]],
  ['nk_5fgroup_5fscrolled_5fbegin_41',['# nk_group_scrolled_begin',['../nuklear__group_8c.html#autotoc_md83',1,'']]],
  ['nk_5fgroup_5fscrolled_5fend_42',['# nk_group_scrolled_end',['../nuklear__group_8c.html#autotoc_md84',1,'']]],
  ['nk_5fgroup_5fscrolled_5foffset_5fbegin_43',['# nk_group_scrolled_offset_begin',['../nuklear__group_8c.html#autotoc_md82',1,'']]],
  ['nk_5fgroup_5fset_5fscroll_44',['# nk_group_set_scroll',['../nuklear__group_8c.html#autotoc_md86',1,'']]],
  ['nk_5fhandle_45',['nk_handle',['../unionnk__handle.html',1,'']]],
  ['nk_5fimage_46',['nk_image',['../structnk__image.html',1,'']]],
  ['nk_5finit_47',['nk_init',['../nuklear__context_8c.html#autotoc_md14',1,'']]],
  ['nk_5finit_5ffixed_48',['nk_init_fixed',['../nuklear__context_8c.html#autotoc_md13',1,'']]],
  ['nk_5finput_49',['nk_input',['../structnk__input.html',1,'']]],
  ['nk_5finput_5fis_5fmouse_5fhovering_5fdelay_5frect_50',['nk_input_is_mouse_hovering_delay_rect',['../nuklear__input_8c.html#autotoc_md20',1,'']]],
  ['nk_5finput_5fis_5fmouse_5fhovering_5fstill_5fdelay_5fclicked_5frect_51',['nk_input_is_mouse_hovering_still_delay_clicked_rect',['../nuklear__input_8c.html#autotoc_md22',1,'']]],
  ['nk_5finput_5fis_5fmouse_5fhovering_5fstill_5fdelay_5frect_52',['nk_input_is_mouse_hovering_still_delay_rect',['../nuklear__input_8c.html#autotoc_md21',1,'']]],
  ['nk_5finput_5fis_5fmouse_5fhovering_5fstill_5frect_53',['nk_input_is_mouse_hovering_still_rect',['../nuklear__input_8c.html#autotoc_md19',1,'']]],
  ['nk_5fitem_5fis_5fany_5factive_54',['# nk_item_is_any_active',['../nuklear__window_8c.html#autotoc_md51',1,'']]],
  ['nk_5fkey_55',['nk_key',['../structnk__key.html',1,'']]],
  ['nk_5fkeyboard_56',['nk_keyboard',['../structnk__keyboard.html',1,'']]],
  ['nk_5flayout_5frow_5ftemplate_5fbegin_57',['# nk_layout_row_template_begin',['../nuklear__layout_8c.html#autotoc_md65',1,'']]],
  ['nk_5flayout_5frow_5ftemplate_5fend_58',['# nk_layout_row_template_end',['../nuklear__layout_8c.html#autotoc_md69',1,'']]],
  ['nk_5flayout_5frow_5ftemplate_5fpush_5fdynamic_59',['# nk_layout_row_template_push_dynamic',['../nuklear__layout_8c.html#autotoc_md66',1,'']]],
  ['nk_5flayout_5frow_5ftemplate_5fpush_5fstatic_60',['# nk_layout_row_template_push_static',['../nuklear__layout_8c.html#autotoc_md68',1,'']]],
  ['nk_5flayout_5frow_5ftemplate_5fpush_5fvariable_61',['# nk_layout_row_template_push_variable',['../nuklear__layout_8c.html#autotoc_md67',1,'']]],
  ['nk_5flayout_5fspace_5fbegin_62',['# nk_layout_space_begin',['../nuklear__layout_8c.html#autotoc_md70',1,'']]],
  ['nk_5flayout_5fspace_5fbounds_63',['# nk_layout_space_bounds',['../nuklear__layout_8c.html#autotoc_md73',1,'']]],
  ['nk_5flayout_5fspace_5fend_64',['# nk_layout_space_end',['../nuklear__layout_8c.html#autotoc_md72',1,'']]],
  ['nk_5flayout_5fspace_5fpush_65',['# nk_layout_space_push',['../nuklear__layout_8c.html#autotoc_md71',1,'']]],
  ['nk_5flayout_5fspace_5frect_5fto_5flocal_66',['# nk_layout_space_rect_to_local',['../nuklear__layout_8c.html#autotoc_md77',1,'']]],
  ['nk_5flayout_5fspace_5frect_5fto_5fscreen_67',['# nk_layout_space_rect_to_screen',['../nuklear__layout_8c.html#autotoc_md76',1,'']]],
  ['nk_5flayout_5fspace_5fto_5flocal_68',['# nk_layout_space_to_local',['../nuklear__layout_8c.html#autotoc_md75',1,'']]],
  ['nk_5flayout_5fspace_5fto_5fscreen_69',['# nk_layout_space_to_screen',['../nuklear__layout_8c.html#autotoc_md74',1,'']]],
  ['nk_5flist_5fview_70',['nk_list_view',['../structnk__list__view.html',1,'']]],
  ['nk_5fmemory_71',['nk_memory',['../structnk__memory.html',1,'']]],
  ['nk_5fmemory_5fstatus_72',['nk_memory_status',['../structnk__memory__status.html',1,'']]],
  ['nk_5fmenu_5fstate_73',['nk_menu_state',['../structnk__menu__state.html',1,'']]],
  ['nk_5fmouse_74',['nk_mouse',['../structnk__mouse.html',1,'']]],
  ['nk_5fmouse_5fbutton_75',['nk_mouse_button',['../structnk__mouse__button.html',1,'']]],
  ['nk_5fnine_5fslice_76',['nk_nine_slice',['../structnk__nine__slice.html',1,'']]],
  ['nk_5fpage_77',['nk_page',['../structnk__page.html',1,'']]],
  ['nk_5fpage_5fdata_78',['nk_page_data',['../unionnk__page__data.html',1,'']]],
  ['nk_5fpage_5felement_79',['nk_page_element',['../structnk__page__element.html',1,'']]],
  ['nk_5fpanel_80',['nk_panel',['../structnk__panel.html',1,'']]],
  ['nk_5fpanel_5fflags_81',['nk_panel_flags',['../Window.html#autotoc_md25',1,'']]],
  ['nk_5fpool_82',['nk_pool',['../structnk__pool.html',1,'']]],
  ['nk_5fpopup_5fbuffer_83',['nk_popup_buffer',['../structnk__popup__buffer.html',1,'']]],
  ['nk_5fpopup_5fstate_84',['nk_popup_state',['../structnk__popup__state.html',1,'']]],
  ['nk_5fproperty_85',['nk_property',['../unionnk__property.html',1,'']]],
  ['nk_5fproperty_5fdouble_86',['# nk_property_double',['../nuklear__property_8c.html#autotoc_md112',1,'']]],
  ['nk_5fproperty_5ffloat_87',['# nk_property_float',['../nuklear__property_8c.html#autotoc_md111',1,'']]],
  ['nk_5fproperty_5fint_88',['# nk_property_int',['../Properties.html#autotoc_md110',1,'']]],
  ['nk_5fproperty_5fstate_89',['nk_property_state',['../structnk__property__state.html',1,'']]],
  ['nk_5fproperty_5fvariant_90',['nk_property_variant',['../structnk__property__variant.html',1,'']]],
  ['nk_5fpropertyd_91',['# nk_propertyd',['../nuklear__property_8c.html#autotoc_md115',1,'']]],
  ['nk_5fpropertyf_92',['# nk_propertyf',['../nuklear__property_8c.html#autotoc_md114',1,'']]],
  ['nk_5fpropertyi_93',['# nk_propertyi',['../nuklear__property_8c.html#autotoc_md113',1,'']]],
  ['nk_5frect_94',['nk_rect',['../structnk__rect.html',1,'']]],
  ['nk_5frecti_95',['nk_recti',['../structnk__recti.html',1,'']]],
  ['nk_5frow_5flayout_96',['nk_row_layout',['../structnk__row__layout.html',1,'']]],
  ['nk_5fscroll_97',['nk_scroll',['../structnk__scroll.html',1,'']]],
  ['nk_5fspacer_98',['# nk_spacer',['../nuklear__layout_8c.html#autotoc_md78',1,'']]],
  ['nk_5fstr_99',['nk_str',['../structnk__str.html',1,'']]],
  ['nk_5fstyle_100',['nk_style',['../structnk__style.html',1,'']]],
  ['nk_5fstyle_5fbutton_101',['nk_style_button',['../structnk__style__button.html',1,'']]],
  ['nk_5fstyle_5fchart_102',['nk_style_chart',['../structnk__style__chart.html',1,'']]],
  ['nk_5fstyle_5fcombo_103',['nk_style_combo',['../structnk__style__combo.html',1,'']]],
  ['nk_5fstyle_5fedit_104',['nk_style_edit',['../structnk__style__edit.html',1,'']]],
  ['nk_5fstyle_5fitem_105',['nk_style_item',['../structnk__style__item.html',1,'']]],
  ['nk_5fstyle_5fitem_5fdata_106',['nk_style_item_data',['../unionnk__style__item__data.html',1,'']]],
  ['nk_5fstyle_5fknob_107',['nk_style_knob',['../structnk__style__knob.html',1,'']]],
  ['nk_5fstyle_5fprogress_108',['nk_style_progress',['../structnk__style__progress.html',1,'']]],
  ['nk_5fstyle_5fproperty_109',['nk_style_property',['../structnk__style__property.html',1,'']]],
  ['nk_5fstyle_5fscrollbar_110',['nk_style_scrollbar',['../structnk__style__scrollbar.html',1,'']]],
  ['nk_5fstyle_5fselectable_111',['nk_style_selectable',['../structnk__style__selectable.html',1,'']]],
  ['nk_5fstyle_5fslider_112',['nk_style_slider',['../structnk__style__slider.html',1,'']]],
  ['nk_5fstyle_5ftab_113',['nk_style_tab',['../structnk__style__tab.html',1,'']]],
  ['nk_5fstyle_5ftext_114',['nk_style_text',['../structnk__style__text.html',1,'']]],
  ['nk_5fstyle_5ftoggle_115',['nk_style_toggle',['../structnk__style__toggle.html',1,'']]],
  ['nk_5fstyle_5fwindow_116',['nk_style_window',['../structnk__style__window.html',1,'']]],
  ['nk_5fstyle_5fwindow_5fheader_117',['nk_style_window_header',['../structnk__style__window__header.html',1,'']]],
  ['nk_5ftable_118',['nk_table',['../structnk__table.html',1,'']]],
  ['nk_5ftext_119',['nk_text',['../structnk__text.html',1,'']]],
  ['nk_5ftext_5fedit_120',['nk_text_edit',['../structnk__text__edit.html',1,'']]],
  ['nk_5ftext_5fedit_5frow_121',['nk_text_edit_row',['../structnk__text__edit__row.html',1,'']]],
  ['nk_5ftext_5ffind_122',['nk_text_find',['../structnk__text__find.html',1,'']]],
  ['nk_5ftext_5fundo_5frecord_123',['nk_text_undo_record',['../structnk__text__undo__record.html',1,'']]],
  ['nk_5ftext_5fundo_5fstate_124',['nk_text_undo_state',['../structnk__text__undo__state.html',1,'']]],
  ['nk_5ftree_5fimage_5fpush_125',['# nk_tree_image_push',['../nuklear_8h.html#autotoc_md93',1,'']]],
  ['nk_5ftree_5fimage_5fpush_5fhashed_126',['# nk_tree_image_push_hashed',['../nuklear__tree_8c.html#autotoc_md95',1,'']]],
  ['nk_5ftree_5fimage_5fpush_5fid_127',['# nk_tree_image_push_id',['../nuklear_8h.html#autotoc_md94',1,'']]],
  ['nk_5ftree_5fpop_128',['# nk_tree_pop',['../nuklear__tree_8c.html#autotoc_md96',1,'']]],
  ['nk_5ftree_5fpush_129',['# nk_tree_push',['../nuklear_8h.html#autotoc_md90',1,'']]],
  ['nk_5ftree_5fpush_5fhashed_130',['# nk_tree_push_hashed',['../nuklear__tree_8c.html#autotoc_md92',1,'']]],
  ['nk_5ftree_5fpush_5fid_131',['# nk_tree_push_id',['../nuklear_8h.html#autotoc_md91',1,'']]],
  ['nk_5ftree_5fstate_5fimage_5fpush_132',['# nk_tree_state_image_push',['../nuklear__tree_8c.html#autotoc_md98',1,'']]],
  ['nk_5ftree_5fstate_5fpop_133',['# nk_tree_state_pop',['../nuklear__tree_8c.html#autotoc_md99',1,'']]],
  ['nk_5ftree_5fstate_5fpush_134',['# nk_tree_state_push',['../nuklear__tree_8c.html#autotoc_md97',1,'']]],
  ['nk_5ftree_5ftype_135',['nk_tree_type',['../Tree.html#autotoc_md89',1,'']]],
  ['nk_5fuser_5ffont_136',['nk_user_font',['../structnk__user__font.html',1,'']]],
  ['nk_5fvec2_137',['nk_vec2',['../structnk__vec2.html',1,'']]],
  ['nk_5fvec2i_138',['nk_vec2i',['../structnk__vec2i.html',1,'']]],
  ['nk_5fwindow_139',['nk_window',['../structnk__window.html',1,'']]],
  ['nk_5fwindow_5fclose_140',['# nk_window_close',['../nuklear__window_8c.html#autotoc_md57',1,'']]],
  ['nk_5fwindow_5fcollapse_141',['# nk_window_collapse',['../nuklear__window_8c.html#autotoc_md58',1,'']]],
  ['nk_5fwindow_5fcollapse_5fif_142',['# nk_window_collapse_if',['../nuklear__window_8c.html#autotoc_md59',1,'']]],
  ['nk_5fwindow_5ffind_143',['# nk_window_find',['../nuklear__window_8c.html#autotoc_md32',1,'']]],
  ['nk_5fwindow_5fget_5fbounds_144',['# nk_window_get_bounds',['../nuklear__window_8c.html#autotoc_md33',1,'']]],
  ['nk_5fwindow_5fget_5fcanvas_145',['# nk_window_get_canvas',['../nuklear__window_8c.html#autotoc_md42',1,'']]],
  ['nk_5fwindow_5fget_5fcontent_5fregion_146',['# nk_window_get_content_region',['../nuklear__window_8c.html#autotoc_md38',1,'']]],
  ['nk_5fwindow_5fget_5fcontent_5fregion_5fmax_147',['# nk_window_get_content_region_max',['../nuklear__window_8c.html#autotoc_md40',1,'']]],
  ['nk_5fwindow_5fget_5fcontent_5fregion_5fmin_148',['# nk_window_get_content_region_min',['../nuklear__window_8c.html#autotoc_md39',1,'']]],
  ['nk_5fwindow_5fget_5fcontent_5fregion_5fsize_149',['# nk_window_get_content_region_size',['../nuklear__window_8c.html#autotoc_md41',1,'']]],
  ['nk_5fwindow_5fget_5fheight_150',['# nk_window_get_height',['../nuklear__window_8c.html#autotoc_md36',1,'']]],
  ['nk_5fwindow_5fget_5fpanel_151',['# nk_window_get_panel',['../nuklear__window_8c.html#autotoc_md37',1,'']]],
  ['nk_5fwindow_5fget_5fposition_152',['# nk_window_get_position',['../nuklear__window_8c.html#autotoc_md34',1,'']]],
  ['nk_5fwindow_5fget_5fscroll_153',['# nk_window_get_scroll',['../nuklear__window_8c.html#autotoc_md43',1,'']]],
  ['nk_5fwindow_5fget_5fsize_154',['# nk_window_get_size',['../nuklear__window_8c.html#autotoc_md35',1,'']]],
  ['nk_5fwindow_5fhas_5ffocus_155',['# nk_window_has_focus',['../nuklear__window_8c.html#autotoc_md44',1,'']]],
  ['nk_5fwindow_5fis_5factive_156',['# nk_window_is_active',['../nuklear__window_8c.html#autotoc_md49',1,'']]],
  ['nk_5fwindow_5fis_5fany_5fhovered_157',['# nk_window_is_any_hovered',['../nuklear__window_8c.html#autotoc_md50',1,'']]],
  ['nk_5fwindow_5fis_5fclosed_158',['# nk_window_is_closed',['../nuklear__window_8c.html#autotoc_md47',1,'']]],
  ['nk_5fwindow_5fis_5fcollapsed_159',['# nk_window_is_collapsed',['../nuklear__window_8c.html#autotoc_md46',1,'']]],
  ['nk_5fwindow_5fis_5fhidden_160',['# nk_window_is_hidden',['../nuklear__window_8c.html#autotoc_md48',1,'']]],
  ['nk_5fwindow_5fis_5fhovered_161',['# nk_window_is_hovered',['../nuklear__window_8c.html#autotoc_md45',1,'']]],
  ['nk_5fwindow_5fset_5fbounds_162',['# nk_window_set_bounds',['../nuklear__window_8c.html#autotoc_md52',1,'']]],
  ['nk_5fwindow_5fset_5ffocus_163',['# nk_window_set_focus',['../nuklear__window_8c.html#autotoc_md55',1,'']]],
  ['nk_5fwindow_5fset_5fposition_164',['# nk_window_set_position',['../nuklear__window_8c.html#autotoc_md53',1,'']]],
  ['nk_5fwindow_5fset_5fscroll_165',['# nk_window_set_scroll',['../nuklear__window_8c.html#autotoc_md56',1,'']]],
  ['nk_5fwindow_5fset_5fsize_166',['# nk_window_set_size',['../nuklear__window_8c.html#autotoc_md54',1,'']]],
  ['nk_5fwindow_5fshow_167',['# nk_window_show',['../nuklear__window_8c.html#autotoc_md60',1,'']]],
  ['nk_5fwindow_5fshow_5fif_168',['nk_window_show_if',['../nuklear__window_8c.html#autotoc_md61',1,'# nk_window_show_if'],['../nuklear__window_8c.html#autotoc_md62',1,'# nk_window_show_if']]],
  ['nuklear_169',['nuklear',['../md_src_2HEADER.html',1,'Nuklear'],['../index.html',1,'Nuklear']]],
  ['nuklear_20font_20baker_170',['Nuklear font baker',['../Font.html#autotoc_md118',1,'']]]
];
