name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: "${{ secrets.GITHUB_TOKEN }}"
